EventName = "LlmCompletion"
MessageEventName = "LlmChatCompletionMessage"
SummaryEventName = "LlmChatCompletionSummary"
EmbeddingEventName = "LlmEmbedding"
VectorSearchEventName = "LlmVectorSearch"
VectorSearchResultsEventName = "LlmVectorSearchResult"
TransactionBeginEventName = "LlmTransactionBegin"
